name: uva

defaults:
  - _self_
  - task: umi_multi_tactile
  - model: uva_tactile

dataloader:
  batch_size: 32
  num_workers: 12
  persistent_workers: false
  pin_memory: true
  shuffle: true

val_dataloader:
  batch_size: 32
  num_workers: 8
  persistent_workers: false
  pin_memory: true
  shuffle: false

training:
  checkpoint_every: 1
  debug: false
  device: cuda:0
  gradient_accumulate_every: 1
  lr_scheduler: cosine
  lr_warmup_steps: 1000
  max_train_steps: null
  max_val_steps: null
  num_epochs: 200
  resume: true
  reset_lr: true
  rollout_every: 1
  sample_every: 5
  seed: 42
  tqdm_interval_sec: 1.0
  use_ema: true
  val_every: 1
  mixed_precision: 'bf16'
  deepspeed_config: unified_video_action/config/zero2.json
  
checkpoint:
  save_last_ckpt: true
  save_last_snapshot: false
  topk:
    monitor_key: valid_mse_loss
    format_str: epoch={epoch:04d}-mse={valid_mse_loss:.6f}.ckpt
    k: 10
    mode: min


ema:
  _target_: unified_video_action.model.autoregressive.ema_model.EMAModel
  inv_gamma: 1.0
  max_value: 0.9999
  min_value: 0.0
  power: 0.75
  update_after_step: 0

logging:
  group: null
  id: null
  mode: online
  name: train_uva_umi_tactile
  project: uva_tactile
  resume: true
  tags:
  - train_uva_umi_tactile
  - umi_tactile
  - default

multi_run:
  run_dir: data/outputs/train_uva_umi_tactile
  wandb_name_base: train_uva_umi_tactile